apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: galaxy-ui
  name: galaxy-ui
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: quay.io/danclark/galaxy-static:latest
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
