apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: galaxy-dev
  name: galaxy-dev
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: quay.io/ansiblegalaxy/galaxy-dev:latest
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
