apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: galaxy-pulp-worker
  name: galaxy-pulp-worker
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: quay.io/ansiblegalaxy/galaxy:latest
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
