apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: influxdb
  name: influxdb
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: influxdb:latest
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
