---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --provider openshift convert --file /home/ec2-user/workspace/galaxy/scripts/docker/release/compose.yml
      --replicas 1 --volumes persistentVolumeClaim
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: influxdb
  name: influxdb
spec:
  ports:
  - name: "influx"
    port: 8086
    targetPort: 8086
  selector:
    io.kompose.service: influxdb
status:
  loadBalancer: {}
