apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose --provider openshift convert --file /home/ec2-user/workspace/galaxy/scripts/docker/release/compose.yml
      --replicas 1 --volumes persistentVolumeClaim
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: influxdb
  name: influxdb
spec:
  replicas: 1
  selector:
    io.kompose.service: influxdb
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: influxdb
    spec:
      containers:
      - env:
        - name: INFLUXDB_ADMIN_PASSWORD
          value: admin
        - name: INFLUXDB_ADMIN_USER
          value: admin
        - name: INFLUXDB_DB
          value: galaxy
        - name: INFLUXDB_REPORTING_DISABLED
          value: "true"
        - name: INFLUXDB_WRITE_USER
          value: galaxy
        - name: INFLUXDB_WRITE_USER_PASSWORD
          value: galaxy
        image: ' '
        name: influxdb
        ports:
        - containerPort: 8086
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - influxdb
      from:
        kind: ImageStreamTag
        name: influxdb:latest
    type: ImageChange
status: {}
